var prompts = [
    'We could’ve shipped more often today.',
    'We Ping Pong-paired very well today.',
    'We went down a lot of rabbit holes today.',
    'We found clearly scoped stories in our backlog to pick up today.',
    'This week so far, we had quite a lot of churn in our prioritization.',
    'This week, I feel like we had a lot of meetings.',
    'This week, we never had a broken build.',
    'This week, we spent a lot of time on chores.',
    'Today, our flow was quite bad compared to other days.',
    'Today it wasn’t easy to get to a consensus during discussions.',
    'We were really discussing things quite a long time today.',
    'I loved how we got to agree on every topic today very quickly.',
    'We were boy-scouting the code really well today.',
    'We cut quite a few corners here and there.',
    'We went out of scope for the story at least one time today.',
    'We could improve our temper control a bit.',
    'Today was a pretty frustrating day.',
    'Today was the best day of the week so far.',
    'Today was the worst day for quite some time.',
    'We delivered a story today.',
    'We did not ship anything today.',
    'Remember that story we shipped this week but it then got rejected...',
    'I still have question marks for certain aspects of the technology we employed.',
    'We did a lot of user interviews this week, you did very good.',
    'I feel we have been nice with each other.',
    'Today, I learned how to ...',
    'Today, I taught you how to ...',
    'I appreciate that you always ...',
    'We did take a Ping Pong break today.',
    'We have paid back technical debt today.',
    'We did accrue technical debt today.',
    'We both are comfortable with our pairing and break rhythm.',
    'One of us was exhausted at some point during the day because we haven’t taken a break soon enough.',
    'I feel we’ve been both equally engaged today.',
    'We both are making sure we’re moving forward and share the responsibility.',
    'We are doing well maintaining symbols.',
    'Design review went really good this week.',
    'Pairing with (Design / Dev / PM) went really well.',
    'Really interesting that article you shared.',
    'Why didn’t we pair on that?',
    'I am comfortable explaining our technology to somebody else.'
]
