var prompts = [
    "We could've shipped more often today.",
    "We Ping Pong-paired very well today.",
    "We went down a lot of rabbit holes today.",
    "We found clearly-scoped stories in our backlog to pick up today.",
    "We had quite a lot of churn in our prioritization this week.",
    "I feel like we're having a lot of meetings this week.",
    "We never had a broken build this week.",
    "We spent a lot of time on chores this week.",
    "Today's flow was quite bad compared to other days.",
    "Reaching a consensus during today's discussion wasn't easy.",
    "We were really discussing quite a lot today.",
    "I love how we agreed on every topic very quickly today.",
    "We were boy-scouting the code really well today.",
    "We cut quite a few corners here and there.",
    "We went out of scope for the story at least one time.",
    "We could control our temper a little better.",
    "Let's high-five.",
    "Today was a pretty frustrating day.",
    "Today was the best day of the week so far.",
    "Today was the worst day for quite some time.",
    "We delivered a story today.",
    "We did not ship anything today.",
    "Remember that story we shipped this week but then it got rejected... ?",
    "I still have questions about certain aspects of our technology.",
    "We did a lot of user-interviews this week.",
    "I feel we have been kind to each other.",
    "Today I learned how to ...",
    "I feel I did a good job explaining ... to you.",
    "Thank you for being my pair.",
    "I appreciate that you ...",
    "We did take a Ping Pong break today.",
    "We paid back technical debt today.",
    "We accrued technical debt today.",
    "We are both comfortable with our pairing and break rhythm.",
    "I was exhausted at some point during the day because we haven't taken a break soon enough.",
    "I feel we've both been equally engaged today.",
    "We're both making sure we move forward and share responsibilities.",
    "We are doing well maintaining symbols in Sketch.",
    "Design review went really well this week.",
    "Cross discipline pairing went really well.",
    "We haven't really paired across disciplines this week.",
    "Thanks for sharing that interesting article.",
    "Why didn't we pair on that thing the other day?",
    "I am comfortable explaining all of our technology to somebody else.",
    "I can explain to a passer-by what we’re working on now and what’s next for the product.",
    "We paired for a significant part of the day.",
    "We shared the “driver” role while pairing today.",
    "The backlog is healthy.",
    "We were on top of story acceptance today.",
    "We should make sure we don’t run out of stories this week.",
    "We focused on the most important thing today.",
    "I felt productive today!",
    "I liked how you facilitated… (e.g. IPM, retro)",
    "It felt like we’re on the same wave-length today.",
    "If we could improve one thing about how we worked today, it would be ...",
    "We should definitely keep doing ...",
    "We should really think about kicking ...",
    "We accepted some stories today.",
    "We are doing well at keeping our tests readable.",
    "We are doing well at keeping our code readable.",
    "We broke a lot of tests today.",
    "Our tests are amazingly stable.",
    "We had to change quite a few seemingly unrelated tests today.",
    "We haven't really followed YAGNI today.",
    "I think we overcomplicated [...] today.",
    "We should invest more time in automation.",
    "Our discussions felt a little rough today.",
    "You made a really good point today about [...].",
    "I noticed how you are working on [...].",
    "There were a lot of disruptions today.",
    "We had clearly defined acceptance criteria for our last story.",
    "There was quite a bit of uncertainty during IPM this week.",
    "We all pointed very consistently during our last IPM.",
    "There was a noticeable difference in everyone's story pointing this IPM.",
    "The article you shared was really interesting.",
    "We should do more of [...].",
    "We should do less of [...].",
    "How do you think I handled [...] today?",
    "I like how you handled [...] today, because [...].",
    "I hope me talking about [...] was useful?",
    "How could I improve next time, when I talk about something similar to [...] again?"
]
