var prompts = [
    "We could've shipped more often today.",
    "We Ping Pong-paired very well today.",
    "We went down a lot of rabbit holes today.",
    "We found clearly-scoped stories in our backlog to pick up today.",
    "We had quite a lot of churn in our prioritization this week.",
    "I feel like we're having a lot of meetings this week.",
    "We never had a broken build this week.",
    "We spent a lot of time on chores this week.",
    "Today's flow was quite bad compared to other days.",
    "Reaching a consensus during today's discussion wasn't easy.",
    "We were really discussing quite a lot today.",
    "I love how agreed on every topic very quickly today.",
    "We were boy-scouting the code really well today.",
    "We cut quite a few corners here and there.",
    "We went out of scope for the story at least one time.",
    "We could control our temper a little better.",
    "Let's high-five.",
    "Today was a pretty frustrating day.",
    "Today was the best day of the week so far.",
    "Today was the worst day for quite some time.",
    "We delivered a story today.",
    "We did not ship anything today.",
    "Remember that story we shipped this week but then it got rejected... ?",
    "I still have questions about certain aspects of our technology.",
    "We did a lot of user-interviews this week.",
    "I feel we have been kind to each other.",
    "Today I learned how to ...",
    "I feel I did a good job explaining ... to you.",
    "Thank you for being my pair.",
    "I appreciate that you ...",
    "We did take a Ping Pong break today.",
    "We paid back technical debt today.",
    "We accrued technical debt today.",
    "We are both comfortable with our pairing and break rhythm.",
    "I was exhausted at some point during the day because we haven't taken a break soon enough.",
    "I feel we've both been equally engaged today.",
    "We're both making sure we move forward and share responsibilities.",
    "We are doing well maintaining symbols in Sketch.",
    "Design review went really well this week.",
    "Cross discipline pairing went really well.",
    "We haven't really paired across disciplines this week.",
    "Thanks for sharing that interesting article.",
    "Why didn't we pair on that thing the other day?",
    "I am comfortable explaining all of our technology to somebody else."
]
